database:
  host: localhost
  port: 3306
  name: bankA_db
  user: root
  pass: password
port: 8001
org:
  orgType: BANK
  orgId: 100001
  signMethod: EDDSA
  privateKey: "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIHDyl8knmPmBZecbV6Hntwq3QWP8RE8JwUo4BCLzFx0o\n-----END PRIVATE KEY-----"