database:
  host: localhost
  port: 3306
  name: bankB_db
  user: root
  pass: password
port: 8002
org:
  orgType: BANK
  orgId: 100002
  signMethod: ECDSA
  privateKey: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIFzwqp2YUrJhhIJIw/CS6zfBkQ7tCkr28yt0BAYPhOkDoAoGCCqGSM49\nAwEHoUQDQgAEvhLPoXgpW25cTnbBcnSFmDkzDgS0b5cgEhB82zSN+epJcVq12Bi+\nvivcrLXP9NpjSrQxhKkc1lI27AU8RE3Tqw==\n-----END EC PRIVATE KEY-----"
