database:
  host: localhost
  port: 3306
  name: bankB_db
  user: root
  pass: password
port: 8002
org:
  orgType: BANK
  orgId: 100002
  signMethod: ECC
  privateKey: -----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIFiCZf14s1fqpb3JE58YXBL4a5qztVyw8Oqr6HQTGiRfoAoGCCqGSM49\nAwEHoUQDQgAEQ1jXQF7g0L3gbbbSBbu5YV9ZwAgNNKj3PJc1K/ntoNx6w2mL40HX\n1RyhxSCj1XEkRcY8FcgSsmtMYNjcNQUTLw==\n-----END EC PRIVATE KEY-----
